# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 18:56
from __future__ import unicode_literals

import bumf.core.models.auth
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nick', models.CharField(help_text='Please use only characters in the latin alphabet, plus numbers and _-.', max_length=60, unique=True, validators=[bumf.core.models.auth.nick_validator], verbose_name='Nick name')),
                ('first_name', models.CharField(blank=True, help_text='Please enter your real first name.', max_length=120, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, help_text='Your email address will only be stored for password restores and emergency notifications.', max_length=254, null=True, verbose_name='E-Mail')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
