# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170108_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Project'),
            preserve_default=False,
        ),
    ]
