# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dossier_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
