# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170201_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
