# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_virtualaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('variant', models.CharField(choices=[('bank', 'bank'), ('cash', 'cash')], default='bank', max_length=4)),
                ('import_transactions', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='real_accounts', to='core.Project')),
            ],
        ),
    ]
